### ISSUE TITLE
Is Git LFS supported?

### ISSUE THREAD

**Issue by mloskot** [theonedev/onedev#1]
Is there any support for Git LFS storage?

This features seems not mentioned anywhere, so I assume it is not supported. If so, is there any roadmap related?

**Comment by robinshine** [comment]
Will investigate in our next release cycle

**Comment by robinshine** [comment]
@mloskot for dogfooding purpose, let's collaborate at code.onedev.io. I duplicated this issue there:
https://code.onedev.io/projects/onedev-server/issues/2/activities
