### ISSUE TITLE
add issue state  tbc,how to show issue list.

### ISSUE THREAD

**Issue by FoxesChen** [theonedev/onedev#10]
我在issue管理里面加了一个state，叫TBC，怎么样才能加到ISSUE里面。并且改变这个issue的state 为TBC，现在issue变更里面只有open 和 close，大体上，我摸会的，但还有点模糊，有没有相关教程之类的。介绍下issue setting 这个里面的功能。

**Comment by robinshine** [comment]
需要在issue transition的页面定义怎样用这个state。
