### ISSUE TITLE
lost issue img.

### ISSUE THREAD

**Issue by FoxesChen** [theonedev/onedev#11]
这次服务器并没有重启，就发生的图片丢失的情况 。是不是服务器有定时清理图片的机制 或清理图片缓存的机制？

**Comment by robinshine** [comment]
是有定时清理的机制，但清理的是过期不用的图片。精力有限，希望能提供复现这个问题的详细步骤，这样我改起来也少花点时间。

**Comment by FoxesChen** [comment]
配置中，有没有什么标记，来启动 /关闭这个定时清理的机制的。之前遇到这个问题，是在服务器重启后，图片丢失，但现在没有重启，就莫名奇妙的出现丢失的情况。

**Comment by robinshine** [comment]
现在没有。保存了以后正常显示，然后过一段时间以后再刷新页面，图片就没有了是这样吗？

**Comment by FoxesChen** [comment]
是的。不知道是怎么回事，有点莫名奇秒的。

**Comment by robinshine** [comment]
2.0.8 解决了这个bug

**Comment by FoxesChen** [comment]
赞
