### ISSUE TITLE
Able to import/export projects between OneDev and other products

### ISSUE THREAD

**Issue by robinshine** [theonedev/onedev#20]
It will be convenient to be able to import/export projects between OneDev and other products such as GitHub/GitLab/BitBucket etc.

**Comment by ablekh** [comment]
I think that labeling this feature as being "convenient" is an understatement. :-)

**Comment by robinshine** [comment]
In order to dogfood OneDev, we will develop at code.onedev.io. This issue is duplicated there as:
https://code.onedev.io/projects/onedev-server/issues/4/activities
