### ISSUE TITLE
It’s a merge request and not a pull request

### ISSUE THREAD

**Issue by ad-si** [theonedev/onedev#23]
Please don’t make the same mistake as GitHub. They stole the term from git, but in git it really is a pull request whereas that what is provided on a hosting platform is a merge request. GitLab got it right.

**Comment by robinshine** [comment]
I initially uses the term "Merge Request". However since a "Merge Request" can be merged/squashed/rebased into target branch. I changed to use the neutral word "Pull" to not indicate that there is only a "Merge" approach.

**Comment by ad-si** [comment]
But when it’s squashed or rebased the individual commits are still merged into the target branch. So I think the term is still correct. However, never gets anything pulled, so the term makes just no sense to begin with...

**Comment by robinshine** [comment]
Rebase will replay commits on top of target branch to create linear history. It is not a merge operation. Also since pull request is already a widely accepted terminology, I will stick to use this unless there is other reasons.

**Comment by ad-si** [comment]
> Rebase will replay commits on top of target branch to create linear history. It is not a merge operation.

Mh, interesting viewpoint. But then I wonder if there is an even better term than merge or pull?
Maybe something like improvement proposal / code proposal / patch proposal / patch request
On the other hand if you understand the word merge like a layman than it's even correct with a rebase. External commits were merged into the code base.

> Also since pull request is already a widely accepted terminology, I will stick to use this unless there is other reasons.

Sure, understandable. I'm just really into bike shedding 😅. How can we hope to build a good Nuclear power-plant if we can't even get the color of the bike shed right 😉.

**Comment by robinshine** [comment]
Your suggestion is very welcome, and has its valid points definitely. Just that pull request is already an established concept, we can mention it without any extra explanation, while other terminologies may need to be. Not a perfect world...
