### ISSUE TITLE
A few UI nits

### ISSUE THREAD

**Issue by abathur** [theonedev/onedev#25]
I like the broad strokes of the UI, but noticed a few small things I thought were worth drawing attention to. I've used fairly narrow screen widths mainly for screenshot size, and used a rule to separate distinict thoughts.

----
<img width="616" alt="Screen Shot 2020-01-18 at 9 02 48 AM" src="https://user-images.githubusercontent.com/2548365/72665973-292e3c00-39d3-11ea-9fb3-25c01507e8fa.png">
I see 2 things here:

- The spacing, alignment, and color of the "queries" button and the search box could better communicate their logical relationship.
- The visual harmony can be improved a little by placing the search box and project table on the same vertical line.

Here's an example of what I mean:
<img width="617" alt="Screen Shot 2020-01-18 at 9 12 24 AM" src="https://user-images.githubusercontent.com/2548365/72665975-29c6d280-39d3-11ea-90cd-4f95f073eb63.png">

---
<img width="897" alt="Screen Shot 2020-01-18 at 9 13 09 AM" src="https://user-images.githubusercontent.com/2548365/72665974-29c6d280-39d3-11ea-9170-a3698e2b9e26.png">

I took this screenshot right before the breakpoint that hides the "Last Update" column just to point out how much space is still left. I think the column is useful, so it may be worth preserving at smaller widths. To that end, I see a few optimizations that might help carve out space for it at smaller widths:

- Hide the owner avatar
- Use "Updated" instead of "Last Update"
- Drop the "ago"
- Use a terse time format that abbreviates days/weeks/months/years, like <1d, 5d, 6m, etc.

The "Last Update" column items might be easier to achieve by just generating and hiding a duplicate version of the column and switching between them at narrow widths.

---
<img width="677" alt="Screen Shot 2020-01-18 at 9 46 25 AM" src="https://user-images.githubusercontent.com/2548365/72666403-81ffd380-39d7-11ea-98e7-b11a3a00e670.png">

I see two things here:

1. The highlight when we hover over a commit row has an uncomfortably tight right/left margin.
2. The buttons on each commit row can turn into a mess with longer commit messages. Some things that may help:

    - Collapse the commit-ref copy button into the commit button (tap/click the commit button to see a pop-up choice between copy and visit?)
    - Collapsing the buttons into one menu
    - Collapse tags into a pop-up menu that lists all tags when clicked/touched
    - Truncate commit titles (perhaps at 50 characters, as a kind nudge to users?)

---
Finally, the only thing I went looking for that I found confusing was something like the github "releases" page for a project. It may be that you intend builds or tags to do that duty (and that may be more obvious with more releases in the system?), but I think it provides a useful signal about a project.

**Comment by robinshine** [comment]
Thanks for the insight. The table showing project list has a small margin as I reserve it to show the new event indicator (the blue edge as shown here: https://github.com/theonedev/onedev#painless-pull-request-review). 

As to spacing and color of query button and search box, do you have any suggestions? I am an engineering guy without too many UX senses. Will definitely need help in this area. 

For the commits part, that is definitely needed to be improved. 

For the releases page, it is only a customizable query, the query is named "Releases". One can select to use any other desired name appropriate.

**Comment by robinshine** [comment]
To dogfood OneDev, we will develop at code.onedev.io. I duplicated this issue there as:
https://code.onedev.io/projects/onedev-server/issues/8
