### ISSUE TITLE
Support for aarch64/arm64

### ISSUE THREAD

**Issue by Talinx** [theonedev/onedev#26]
Starting the server (from the zip archive or docker) on an aarch64 CPU results in an error message.
Support for 64 bit ARM CPUs would be useful.

**Comment by robinshine** [comment]
What is the error message when running as docker and running from zip archive?

**Comment by Talinx** [comment]
Error message with docker (some files are downloaded and extracted before this comes up):
`standard_init_linux.go:211: exec user process caused "exec format error"`  
`failed to resize tty, using default size`

Error message from zip archive:
`Unable to locate any of the following binaries:`  
`  /home/chris/onedev-3.0.4/bin/../boot/wrapper-linux-aarch64-`  
`  /home/chris/onedev-3.0.4/bin/../boot/wrapper-linux-aarch64-32`  
`  /home/chris/onedev-3.0.4/bin/../boot/wrapper`

OS: [Fedora Server 31](https://fedoraproject.org/wiki/Architectures/ARM/Raspberry_Pi?rd=Raspberry_Pi#aarch64_supported_images_for_Raspberry_Pi_3)
I used a Raspberry Pi 3 Model B+. (I know that it only got 1 GB of RAM, I wanted to test it before purchasing a SBC with more RAM.)

**Comment by robinshine** [comment]
The library used by OneDev for service wrapping currently does not support this platform. Contacted JSW support and hope they can add this support in future versions.

**Comment by Talinx** [comment]
Thank you!

**Comment by robinshine** [comment]
Good news from JSW support: the latest version supports aarch64. Reopen and will upgrade to latest JSW library in next patch release.

**Comment by robinshine** [comment]
To dogfood OneDev, we will develop at code.onedev.io. I duplicated this issue there as:
https://code.onedev.io/projects/onedev-server/issues/9
