### ISSUE TITLE
Update developer documentation

### ISSUE THREAD

**Issue by bitstorm** [theonedev/onedev#29]
Hi,

I'd like to work with the codebase of the project, for example I'd like to start OneDev from IDE in debug mode. I see there is some developer documentation, but the '[set up environment](https://code.onedev.io/projects/onedev-manual/blob/master/pages/development-environment-setup.md)' document seems a little bit outdated and I couldn't manage to bootstrap OneDev from my IDE (Eclipse). 
Could somebody provide updated instructions?

Thank you.

**Comment by robinshine** [comment]
Documentation updated now and it works on my side following the instructions. If still not work at your side, please post screenshot of the error.

**Comment by bitstorm** [comment]
Hi @robinshine and thank you for your quick reply. I've tried again with the new instructions but I still have an exception inside bootstrap class io.onedev.commons.launcher.bootstrap.Bootstrap. The exception is :

java.lang.RuntimeException: Unable to find product directory.
	at io.onedev.commons.launcher.bootstrap.Bootstrap.main(Bootstrap.java:74)

The bootstrap class is from jar commons-launcher-bootstrap-1.1.9.jar.  Here is the screenshot of my ide with the code line that throws the exception:

![Screenshot from 2020-01-21 17-00-41](https://user-images.githubusercontent.com/536912/72823350-daeb9800-3c73-11ea-87f5-104e585ce75a.png)

**Comment by robinshine** [comment]
I added a section [Error Diagnostics](https://code.onedev.io/projects/onedev-manual/blob/master/pages/development-environment-setup.md#error-diagnostics) in the doc. Please check if it helps.

**Comment by bitstorm** [comment]
Much better! The second point of 'Error Diagnostics' was fundamental. If you agree I will close this issue.
