### ISSUE TITLE
原有gitlab-api是否支持？

### ISSUE THREAD

**Issue by rechardwang** [theonedev/onedev#45]
我在使用gitlab-api的时候 调用onedev的地址如：https://xxx.onedev.com 使用的是access token，报错404，还是说onedev api接口不是访问地址？

**Comment by robinshine** [comment]
为更多测试OneDev，讨论或创建issue请移步https://code.onedev.io/projects/onedev-server/issues/list?query=%22State%22+is+%22Open%22

目前OneDev还没有API可用，具体需求请在这里详述：
https://code.onedev.io/projects/onedev-server/issues/227/activities
