### ISSUE TITLE
Can I provide additional language packs to support Chinese?

### ISSUE THREAD

**Issue by qcjxberin** [theonedev/onedev#6]
Can I provide additional language packs to support Chinese?

**Comment by robinshine** [comment]
现在还不行，但3.0会加上中文支持。

**Comment by qcjxberin** [comment]
那有实现派生仓库及合并派生仓库请求的功能计划吗？

**Comment by robinshine** [comment]
你是指fork吧，现在就有这个功能的:
![image](https://user-images.githubusercontent.com/3423576/52949655-e07f9480-33b7-11e9-9ca7-c85d0967dc85.png)

**Comment by qcjxberin** [comment]
原来在这里，我说怎么没找到呢。

**Comment by qcjxberin** [comment]
等你中文版出来之后正式推着用一用。

**Comment by qcjxberin** [comment]
中文版还没有推出来 吗？

**Comment by robinshine** [comment]
大概六月底

**Comment by robinshine** [comment]
3.0终于是个比较完整的DevOps平台了，下面就开始着手进行多语言支持。

**Comment by robinshine** [comment]
@qcjxberin @tom-chen-cn 为了让OneDev更快的成熟，我们将在OneDev里开发OneDev，我在那里创建了相关的issue:
https://code.onedev.io/projects/onedev-server/issues/3/activities
