### ISSUE TITLE
registered user problem

### ISSUE THREAD

**Issue by 76810490** [theonedev/onedev#7]
when i create new user. i write the field  "FullName"  value is chinese name.and then use this new user login system, then avater look abnormal.

**Comment by robinshine** [comment]
目前中文支持还不好。这种情况下可以上传自己的avatar

**Comment by 76810490** [comment]
哦。还有就是 我用的是 TortoiseGit 这个外壳来操作的。用TortoiseGit创建的标签  和  用 系统中创建的标签 ，好象是不一样的。两者互相看不到。

**Comment by robinshine** [comment]
标签pull/push了吗

**Comment by 76810490** [comment]
原来如此，tks.

**Comment by 76810490** [comment]
感觉还是蛮好用的。除了基本功能，像分支保护，issue功能，issue的邮件提醒， tag，报表的功能。
建议：
1.只要有人提交代码，就有一封电邮发送给整个工程的 “code write” 这个权限的人。
2.语言包：并一定非要自己写，可以把语言文件那块单独做个jar包之类的。
3.插件：把一些功能做成标准API，然后让大家在这个基础之上，做成自己想要的插件。
4.报表：在饼图上显示这个项目上，每个人提交的代码量 ，或提交了多少次。

**Comment by robinshine** [comment]
谢谢使用。好用的话多多介绍给朋友啊，:)
1. Code write 的人可以自己subscribe 任意想要的commit：
![screenshot](https://user-images.githubusercontent.com/3423576/55283166-69aec180-538f-11e9-8b6d-f4a0924560d8.png)
2. 这个会在6月份左右提供
3. 插件体系会在年底提供
4. 目前的contributions图可以显示制定时间段内每个人贡献的大小

**Comment by 76810490** [comment]
必须的推荐呀

**Comment by 76810490** [comment]
今天把服务重启了下。然后发现，在创建ISSUE里面，上传过的图片，会出现丢失的问题。图片会没了。

**Comment by robinshine** [comment]
麻烦重新开个issue，然后写下重现这个问题的步骤。

**Comment by robinshine** [comment]
经测试目前的乱码问题应该是数据库本身的字符集引起的。把数据库默认字符集改成utf8就可以了。

**Comment by 76810490** [comment]
how to do it ?

**Comment by robinshine** [comment]
如果是mysql，百度里搜一下

**Comment by robinshine** [comment]
比如说：
https://www.cnblogs.com/houqi/p/5713176.html
