### ISSUE TITLE
shut down server ,then i found some issue pics lost.

### ISSUE THREAD

**Issue by FoxesChen** [theonedev/onedev#9]
a few days ago, i restart the server , and then i found  some issue pics was lost . it means  can't  preview issue pics.

前几天，我把服务器重启了，然后发现有的ISSUES图片丢失了。无法预览了。 在IE里面显示X。ONEDEV 我已经做成的系统服务。

**Comment by robinshine** [comment]
能重现这个问题吗？我这边测试了几次，并没有发现这个问题。

**Comment by 76810490** [comment]
这个问题，我在本地虚拟机里面，模拟下。看看会不会出现。

**Comment by 76810490** [comment]
我模拟4，5次，也没能重现这个问题。等下次出现这个问题再说吧。

**Comment by robinshine** [comment]
我先close掉，下次出现再重新开
